version: "3.9"

services:
  nginx_main:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

      #ro == readolny ใน ตัว contauber

  app1:
    build: .
    restart: always
    ports:
      - "8081:4000"
  app2:
    build: .
    restart: always
    ports:
      - "8082:4000"
  app3:
    build: .
    restart: always
    ports:
      - "8083:4000"
